services:
  job-tracker-backend:
    image: job-tracker-backend
    ports:
      - "8080:8080"

  frontend:
    image: job-tracker-frontend
    environment:
      - VITE_BACKEND_URL=http://localhost:8080
    ports:
      - "8000:5173"
    depends_on:
      - job-tracker-backend
