# Base image for building the React app
FROM node:18-alpine AS build

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --silent

# Copy source files
COPY . .

# Build the Vite app for production
RUN npm run build

# Development Stage: Use Vite dev server

FROM node:18-alpine AS development

# Set working directory
WORKDIR /app

# Copy dependencies and source files from the build stage
COPY --from=build /app /app

# Expose the development server's default port
EXPOSE 5173

# Start the Vite development server, ensure it listens on all interfaces
CMD ["npm", "run", "dev", "--", "--host"]